# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # Small thumbnail
        thumbnail:
            quality: 85
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: inset

        # Medium resized version
        medium:
            quality: 90
            filters:
                thumbnail:
                    size: [800, 600]
                    mode: inset

        # Large resized version
#        large:
#            quality: 90
#            filters:
#                thumbnail:
#                    size: [1200, 900]
#                    mode: inset
